(function(){
  var JSZIP_CDN = 'https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js';
  function loadJSZip(){
    return new Promise(function(resolve,reject){
      if(window.JSZip) return resolve(window.JSZip);
      var s = document.createElement('script');
      s.src = JSZIP_CDN;
      s.onload = function(){ return window.JSZip ? resolve(window.JSZip) : reject(new Error('no JSZip')); };
      s.onerror = function(){ reject(new Error('failed to load JSZip')); };
      document.head.appendChild(s);
    });
  }
  function uuidv4(){
    if(window.crypto && crypto.randomUUID) try{ return crypto.randomUUID(); }catch(e){}
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){
      var r = Math.random()*16|0, v = c === 'x' ? r : (r&0x3|0x8);
      return v.toString(16);
    });
  }
  function extractNameFromUrl(url){
    try{
      var p = url.split('/');
      var file = p[p.length-1] || '';
      return file.split('.')[0] || 'skin';
    }catch(e){ return 'skin'; }
  }
  var state = {img:null, username:'skin', wrapperId:'mcpack-download-wrapper'};
  function findSkinImage(){
    var imgs = Array.from(document.querySelectorAll('img'));
    for(var i=0;i<imgs.length;i++){
      var im = imgs[i];
      if(!im.src) continue;
      if(im.src.indexOf('textures.minecraft.net') !== -1) return im;
      var meta = (im.alt||'') + ' ' + (im.className||'') + ' ' + (im.id||'') + ' ' + im.src;
      if(/skin|texture|avatar|minecraft/i.test(meta)) return im;
    }
    return null;
  }
  function ensureWrapper(img){
    var existing = document.getElementById(state.wrapperId);
    if(existing){
      existing.dataset.src = img.src || '';
      return existing;
    }
    var wrap = document.createElement('div');
    wrap.id = state.wrapperId;
    wrap.style.display = 'inline-flex';
    wrap.style.gap = '8px';
    wrap.style.marginTop = '8px';
    var btnPng = document.createElement('button');
    btnPng.type = 'button';
    btnPng.id = 'mcpack-btn-png';
    btnPng.textContent = 'Download PNG';
    var btnPack = document.createElement('button');
    btnPack.type = 'button';
    btnPack.id = 'mcpack-btn-mcpack';
    btnPack.textContent = 'Download MCPACK';
    wrap.appendChild(btnPng);
    wrap.appendChild(btnPack);
    wrap.dataset.src = img.src || '';
    img.parentNode && img.parentNode.insertBefore(wrap, img.nextSibling);
    btnPng.addEventListener('click', function(e){ return downloadPNG(img); });
    btnPack.addEventListener('click', function(e){ return downloadMCPackFor(img); });
    return wrap;
  }
  async function downloadPNG(img){
    if(!img || !img.src){ alert('No skin to download'); return; }
    try{
      var r = await fetch(img.src);
      if(!r.ok){ alert('Failed to fetch PNG'); return; }
      var b = await r.blob();
      var name = img.dataset && img.dataset.username ? img.dataset.username : extractNameFromUrl(img.src);
      var a = document.createElement('a');
      a.href = URL.createObjectURL(b);
      a.download = name + '.png';
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(function(){ URL.revokeObjectURL(a.href); }, 5000);
    }catch(e){
      alert('Error downloading PNG');
    }
  }
  async function detectGeometryFromBlob(blob){
    try{
      var bitmap = await createImageBitmap(blob);
      var w = bitmap.width, h = bitmap.height;
      if(h === 32) return 'geometry.humanoid.custom';
      if(w === 64 && h === 64){
        var c = document.createElement('canvas');
        c.width = w; c.height = h;
        var ctx = c.getContext('2d');
        ctx.drawImage(bitmap,0,0);
        try{
          var d = ctx.getImageData(54,20,1,1).data;
          if(d[3] === 0) return 'geometry.humanoid.customSlim';
        }catch(e){}
        return 'geometry.humanoid.custom';
      }
      return 'geometry.humanoid.custom';
    }catch(e){
      return 'geometry.humanoid.custom';
    }
  }
  async function downloadMCPackFor(img){
    if(!img || !img.src){ alert('No skin to pack'); return; }
    var zipLib;
    try{ zipLib = await loadJSZip(); }catch(e){ alert('Failed to load zip library'); return; }
    try{
      var r = await fetch(img.src);
      if(!r.ok){ alert('Failed to fetch skin'); return; }
      var blob = await r.blob();
      var geometry = await detectGeometryFromBlob(blob);
      var uname = img.dataset && img.dataset.username ? img.dataset.username : extractNameFromUrl(img.src);
      var safeName = (uname || 'skin').replace(/[^\w\-_.]/g,'_');
      var skinFilename = safeName + '.png';
      var packName = 'MCBE Skin - ' + (uname || 'Skin');
      var headerUUID = uuidv4();
      var moduleUUID = uuidv4();
      var manifest = {
        format_version: 1,
        header: {
          name: packName,
          description: 'Generated by MCBE Tools Skin Finder',
          uuid: headerUUID,
          version: [1,0,0],
          min_engine_version: [1,16,0]
        },
        modules: [
          { type: 'skin_pack', uuid: moduleUUID, version: [1,0,0] }
        ]
      };
      var serialize = 'mcbe_skin_' + safeName;
      var skinsJson = {
        serialize_name: serialize,
        localization_name: serialize,
        skins: [
          {
            localization_name: uname || 'skin',
            geometry: geometry,
            texture: skinFilename,
            type: 'free'
          }
        ]
      };
      var lang = 'skinpack.' + serialize + '=' + packName + '\n' + 'skin.' + serialize + '.' + (uname || safeName) + '=' + (uname || safeName);
      var zip = new window.JSZip();
      zip.file('manifest.json', JSON.stringify(manifest, null, 2));
      zip.file('skins.json', JSON.stringify(skinsJson, null, 2));
      zip.folder('texts').file('en_US.lang', lang);
      zip.file(skinFilename, blob);
      var out = await zip.generateAsync({type:'blob'});
      var a = document.createElement('a');
      a.href = URL.createObjectURL(out);
      a.download = packName + '.mcpack';
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(function(){ URL.revokeObjectURL(a.href); }, 5000);
    }catch(e){
      alert('Error generating MCPACK');
    }
  }
  function onNewSkinImage(img){
    if(!img) return;
    state.img = img;
    var uname = img.dataset && img.dataset.username ? img.dataset.username : extractNameFromUrl(img.src);
    state.username = uname;
    ensureWrapper(img);
  }
  function observeDOM(){
    var mo = new MutationObserver(function(muts){
      for(var i=0;i<muts.length;i++){
        var m = muts[i];
        if(m.type === 'childList' && m.addedNodes && m.addedNodes.length){
          for(var j=0;j<m.addedNodes.length;j++){
            var node = m.addedNodes[j];
            if(node.nodeType !== 1) continue;
            if(node.tagName === 'IMG' && node.src && (node.src.indexOf('textures.minecraft.net') !== -1 || /skin|texture|avatar|minecraft/i.test(node.alt + ' ' + node.className + ' ' + node.id + ' ' + node.src))){
              node.addEventListener('load', function(){ onNewSkinImage(node); });
              onNewSkinImage(node);
              return;
            }
            try{
              var imgs = node.querySelectorAll && node.querySelectorAll('img');
              for(var k=0;k<(imgs?imgs.length:0);k++){
                var im = imgs[k];
                if(im.src && (im.src.indexOf('textures.minecraft.net') !== -1 || /skin|texture|avatar|minecraft/i.test(im.alt + ' ' + im.className + ' ' + im.id + ' ' + im.src))){
                  im.addEventListener('load', function(){ onNewSkinImage(im); });
                  onNewSkinImage(im);
                  return;
                }
              }
            }catch(e){}
          }
        }
        if(m.type === 'attributes' && m.target && m.target.tagName === 'IMG' && (m.attributeName === 'src' || m.attributeName === 'data-src')){
          var t = m.target;
          if(t.src && (t.src.indexOf('textures.minecraft.net') !== -1 || /skin|texture|avatar|minecraft/i.test(t.alt + ' ' + t.className + ' ' + t.id + ' ' + t.src))){
            onNewSkinImage(t);
            return;
          }
        }
      }
    });
    mo.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['src','data-src'] });
    var periodic = setInterval(function(){
      if(!state.img){
        var found = findSkinImage();
        if(found) onNewSkinImage(found);
      }
    }, 800);
  }
  function moveShowDetails(){
    var all = Array.from(document.querySelectorAll('button,a,span'));
    var btn = all.find(function(el){
      return el.textContent && /show/i.test(el.textContent) && /detail/i.test(el.textContent);
    });
    if(!btn) return;
    var model = document.querySelector('canvas') || document.querySelector('.viewer') || document.querySelector('.model') || document.querySelector('.skin-viewer') || document.querySelector('#skin3d') || document.querySelector('.skin3d');
    if(!model) return;
    if(model.parentNode) model.parentNode.insertBefore(btn, model.nextSibling);
  }
  document.addEventListener('DOMContentLoaded', function(){
    var f = findSkinImage();
    if(f) onNewSkinImage(f);
    observeDOM();
    moveShowDetails();
    setTimeout(moveShowDetails, 800);
  });
})();